/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Pedido;

import java.util.ArrayList;

/**
 *
 * @author lucas
 */
public class Sistema extends javax.swing.JFrame {
    private ArrayList itens = new ArrayList();
    Pedido itemToBeAdd = new Pedido();
    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }
    
    // Clear Inputs
    
    public void clearInputs() {
        this.codeInsert.setText("");
        this.nameInsert.setText("");
        this.valueInsert.setText("");
        this.quantityInsert.setText("");
    }
    
    // add an Product
        
    
    public void addProduct() {
        
        int codeToBeInsert = Integer.parseInt(this.codeInsert.getText());
        int quantityToBeInsert = Integer.parseInt(this.quantityInsert.getText());
        float valueToBeInsert = Float.parseFloat(this.valueInsert.getText());
        String descriptionToBeInsert = this.nameInsert.getText();
        
        itemToBeAdd.addItem(codeToBeInsert, quantityToBeInsert, valueToBeInsert, descriptionToBeInsert);
        itens.add(itemToBeAdd);
        
        this.listShopping();
        this.clearInputs();
    }
    
    public void listShopping() {
        String resultList = itemToBeAdd.getAllItens();
        showItens.setText(resultList);
    }
    
    public void endShopping() {
        
        String s = String.valueOf(itemToBeAdd.getTotal());
        
        resultShopping.setText("R$" + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleText = new javax.swing.JPanel();
        titleTextLabel = new javax.swing.JLabel();
        nameProductLabel = new javax.swing.JLabel();
        valueProductLabel = new javax.swing.JLabel();
        quantityProductLabel = new javax.swing.JLabel();
        codeProductLabel = new javax.swing.JLabel();
        quantityInsert = new javax.swing.JTextField();
        nameInsert = new javax.swing.JTextField();
        valueInsert = new javax.swing.JTextField();
        codeInsert = new javax.swing.JTextField();
        clearInputs = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        showAllitens = new javax.swing.JScrollPane();
        showItens = new javax.swing.JTextArea();
        endShopping = new javax.swing.JButton();
        resultShopping = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleTextLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTextLabel.setText("Sistema de Vendas do IFPB");

        javax.swing.GroupLayout titleTextLayout = new javax.swing.GroupLayout(titleText);
        titleText.setLayout(titleTextLayout);
        titleTextLayout.setHorizontalGroup(
            titleTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleTextLayout.setVerticalGroup(
            titleTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        nameProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameProductLabel.setText("Nome do Produto");

        valueProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueProductLabel.setText("Valor R$");

        quantityProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityProductLabel.setText("Quantidade");

        codeProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codeProductLabel.setText("Código");

        nameInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInsertActionPerformed(evt);
            }
        });

        clearInputs.setText("Limpar");
        clearInputs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearInputsActionPerformed(evt);
            }
        });

        addProduct.setText("Adicionar Item na Compra");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        showItens.setColumns(20);
        showItens.setRows(5);
        showAllitens.setViewportView(showItens);

        endShopping.setText("Finalizar Compra");
        endShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endShoppingActionPerformed(evt);
            }
        });

        resultShopping.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        resultShopping.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(endShopping, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultShopping))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(showAllitens, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(11, 11, 11))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(nameInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nameProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(quantityProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(quantityInsert))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clearInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(valueInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(valueProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(codeInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(codeProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showAllitens, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endShopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultShopping))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInsertActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        this.addProduct();
    }//GEN-LAST:event_addProductActionPerformed

    private void clearInputsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearInputsActionPerformed
        // TODO add your handling code here:
        this.clearInputs();
    }//GEN-LAST:event_clearInputsActionPerformed

    private void endShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endShoppingActionPerformed
        // TODO add your handling code here:
        this.endShopping();
    }//GEN-LAST:event_endShoppingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton clearInputs;
    private javax.swing.JTextField codeInsert;
    private javax.swing.JLabel codeProductLabel;
    private javax.swing.JButton endShopping;
    private javax.swing.JTextField nameInsert;
    private javax.swing.JLabel nameProductLabel;
    private javax.swing.JTextField quantityInsert;
    private javax.swing.JLabel quantityProductLabel;
    private javax.swing.JTextField resultShopping;
    private javax.swing.JScrollPane showAllitens;
    private javax.swing.JTextArea showItens;
    private javax.swing.JPanel titleText;
    private javax.swing.JLabel titleTextLabel;
    private javax.swing.JTextField valueInsert;
    private javax.swing.JLabel valueProductLabel;
    // End of variables declaration//GEN-END:variables
}
