/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author lucas
 */
public class Game extends javax.swing.JFrame {

    int newGameInt = 0;
    int hunches = 0;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    // GERADOR DE NÚMERO ALEATÓRIO
    public static int getRandomNumber(int min, int max) {
        int newRandomNumber = (int) (Math.random() * ((max - min) + 1)) + min;

        return newRandomNumber;
    }

    public void getStarted() {
        if (newGameInt == 0) {
            int newGame = getRandomNumber(1, 10);
            newGameInt = newGame;
        } else {
            this.resultFieldText.setText("Já existe um jogo rodando\nTermine este!");
        }
    }

    public void isMyGuessCorrect() {
        String guess = this.tryInput.getText();
        if (guess == null || guess.contains("")) {
            this.resultFieldText.setText("Insira um valor válido");
        }
        int guessInt = Integer.parseInt(String.valueOf(guess));

        if (guessInt != newGameInt) {
            this.resultFieldText.setText("Você não acertou!");
        } else if (guessInt == newGameInt) {
            String trys = String.valueOf(hunches);
            this.resultFieldText.setText("Você acertou após " + trys + " tentativas!\n\nINICIE UM NOVO JOGO");
            newGameInt = 0;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerTitle = new javax.swing.JPanel();
        titleTextLabel = new javax.swing.JLabel();
        data = new javax.swing.JPanel();
        labelInputTry = new javax.swing.JLabel();
        tryInput = new javax.swing.JTextField();
        resultField = new javax.swing.JScrollPane();
        resultFieldText = new javax.swing.JTextArea();
        startTheGame = new javax.swing.JButton();
        buttonTry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleTextLabel.setFont(new java.awt.Font("AirbusDisp2", 1, 36)); // NOI18N
        titleTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTextLabel.setText("Guess The Number");

        javax.swing.GroupLayout headerTitleLayout = new javax.swing.GroupLayout(headerTitle);
        headerTitle.setLayout(headerTitleLayout);
        headerTitleLayout.setHorizontalGroup(
            headerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerTitleLayout.setVerticalGroup(
            headerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelInputTry.setText("Chute um Número!");

        javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
        data.setLayout(dataLayout);
        dataLayout.setHorizontalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tryInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelInputTry, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataLayout.setVerticalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInputTry, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tryInput, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        resultFieldText.setColumns(20);
        resultFieldText.setRows(5);
        resultField.setViewportView(resultFieldText);

        startTheGame.setText("Iniciar Jogo");
        startTheGame.setAlignmentX(0.5F);
        startTheGame.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        startTheGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTheGameActionPerformed(evt);
            }
        });

        buttonTry.setText("Chutar ");
        buttonTry.setAlignmentX(0.5F);
        buttonTry.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        buttonTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(headerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTry, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startTheGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(headerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTry, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(startTheGame, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTheGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTheGameActionPerformed
        // TODO add your handling code here:
        this.getStarted();
    }//GEN-LAST:event_startTheGameActionPerformed

    private void buttonTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTryActionPerformed
        // TODO add your handling code here:
        this.isMyGuessCorrect();
        hunches += 1;
    }//GEN-LAST:event_buttonTryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTry;
    private javax.swing.JPanel data;
    private javax.swing.JPanel headerTitle;
    private javax.swing.JLabel labelInputTry;
    private javax.swing.JScrollPane resultField;
    private javax.swing.JTextArea resultFieldText;
    private javax.swing.JButton startTheGame;
    private javax.swing.JLabel titleTextLabel;
    private javax.swing.JTextField tryInput;
    // End of variables declaration//GEN-END:variables
}
